### ISSUE TITLE
Skills Icons

### ISSUE THREAD

**Issue by brandynm34** [brandynm34/showOffStatic#102]
Get icons for all skills

Connect check list of skills (in edit portfolio) and have the icons show on public view

**Comment by ChristaFox** [comment]
Combined the user_profile table and the registration table in mongo DB. 
combined the models in the API.
logo for the skills in the angular-src/assets/img/skills.
reorganized this image folder
renamed the file exports in the html and css where they were used.
added docker and git to skills
