### ISSUE TITLE
Site navbar

### ISSUE THREAD

**Issue by brandynm34** [brandynm34/showOffStatic#11]
Logo top left 
Basic search bar top right (search for name)
Shown on dashboard and public view
Has fixed position

![screen shot 2018-02-20 at 10 22 48 am](https://user-images.githubusercontent.com/25212533/36441635-095f6eec-1628-11e8-8c7c-d006fabcda52.png)

**Comment by ChristaFox** [comment]
Issue11SiteNavbar
