### ISSUE TITLE
Advance search

### ISSUE THREAD

**Issue by brandynm34** [brandynm34/showOffStatic#13]
Back button
Be able to search by 
     name 
     linkedin 
     github
     skill checkbox
     twitter handle
     Facebook

search button

![screen shot 2018-02-20 at 11 27 21 am](https://user-images.githubusercontent.com/25212533/36444793-1d124e2e-1631-11e8-8a44-0c101bf6d58d.png)

**Comment by Fleury14** [comment]
I deed eet.
