### ISSUE TITLE
Dashboard view 

### ISSUE THREAD

**Issue by brandynm34** [brandynm34/showOffStatic#14]
Main navbar fixed 

Left side bar
     Edit profile button - leads to edit profile modal 
     Edit portfolio button - leads to edit portfolio modal
     Logout button

Main 
     Main navbar fixed
     Preview of portfolio 
![screen shot 2018-02-20 at 10 50 26 am](https://user-images.githubusercontent.com/25212533/36442886-03d100ae-162c-11e8-8d8a-b598e658fd8a.png)

**Comment by vchho** [comment]
Branched deleted and has been peer reviewed
