### ISSUE TITLE
Register view

### ISSUE THREAD

**Issue by brandynm34** [brandynm34/showOffStatic#16]
Logo 
back button to login page 
Username
First Name 
Last Name 
Password
Confirm password 

Register button
![screen shot 2018-02-20 at 11 00 10 am](https://user-images.githubusercontent.com/25212533/36443312-3cd5a3cc-162d-11e8-9b90-b875ef24a1ba.png)

**Comment by vchho** [comment]
Going to add the back button

**Comment by vchho** [comment]
Finished
